---
# Welcome to Git2Plugin config.
# Configure here the mode of building. Possible modes: ToPhar, ToFolder (DevTools is needed for ToFolder).
building_mode: ToPhar

# Configure here the sources:
srcs: ["https://github.com/BoxOfDevs/Elytra.git", "http://github.com/Ad5001/CustomLogger.git"]

# Time (in minutes) before rechecking plugin updates.
refresh_time: 3
...